version: '3'
services:
  soat3:
    container_name: soat3
    image: franciscosviana/tc-soat3:1.0
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
    networks:
      - soat3
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: soat3
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - soat3

networks:
  soat3:
    driver: bridge
