version: '3'
services:
  soat3:
    container_name: soat3
    image: franciscosviana/tc-soat3:v2
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_HOST=jdbc:mysql://mysqldb:3306/soat3
      - DB_USER=root
      - DB_PASSWORD=root
      - ACCESS_TOKEN_MP=TEST-8555804592568661-101216-ab681ffa7e53364dc510aecee2a4ae6e-99090660
      #DB_PORT: 3306
    networks:
      - soat3
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:8.3.0
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=soat3
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - soat3

networks:
  soat3:
    driver: bridge
