insert into cliente_model (id, nome, cpf, email, telefone, data_hora_criacao, data_hora_alteracao, situacao) values ('1', 'Francisco Viana', '12345678900', 'teste@gmail.com', '11911111111', utc_timestamp, utc_timestamp, true);
insert into cliente_model (id, nome, cpf, email, telefone, data_hora_criacao, data_hora_alteracao, situacao) values ('2', 'Vinicius Junior', '00987654321', 'java@gmail.com', '11922222222', utc_timestamp, utc_timestamp, true);
insert into cliente_model (id, nome, cpf, email, telefone, data_hora_criacao, data_hora_alteracao, situacao) values ('3', 'Isaque Saraiva', '00987654321', 'spring@gmail.com', '11933333333', utc_timestamp, utc_timestamp, true);
insert into cliente_model (id, nome, cpf, email, telefone, data_hora_criacao, data_hora_alteracao, situacao) values ('4', 'Fernanda Freitas', '00987654321', 'docker@gmail.com', '11944444444', utc_timestamp, utc_timestamp, true);
insert into cliente_model (id, nome, cpf, email, telefone, data_hora_criacao, data_hora_alteracao, situacao) values ('5', 'Gabriel Sordi', '00987654321', 'mysql@gmail.com', '11955555555', utc_timestamp, utc_timestamp, true);

insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('1', 'Hot Dog', 'Pão de hot dog, salsicha, vinagrete, purê e batata palha', '', 12.50, 'Lanche', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('2', 'Mega Hamburguer', 'Pão de hamburguer, duas carnes, ketchup, maionese, bacon, tomate, picles', '', 20.00, 'Lanche', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('3', 'Pastel', 'Pastel com o sabor a escolha do cliente', '', 10.00, 'Lanche', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('4', 'Coxinha', 'Coxinha de frango com catupiry', '', 2.50, 'Lanche', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('5', 'Risoli', 'Risoli de presunto com queijo', '', 3.00, 'Lanche', utc_timestamp, utc_timestamp, true);

insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('6', 'Batata frita', 'Porção de batata frita', '', 5.00, 'Acompanhamento', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('7', 'Batata frita com bacon e cheddar', 'Porção de batata frita com bacon e cheddar', '', 10.00, 'Acompanhamento', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('8', 'Onions ', 'Porção de anéis de cebola empanadas', '', 8.50, 'Acompanhamento', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('9', 'Molho especial', 'Molho caseiro com receita do chef da casa', '', 5.00, 'Acompanhamento', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('10', 'Iscas de frango', 'Iscas de frango empanada', '', 7.00, 'Acompanhamento', utc_timestamp, utc_timestamp, true);

insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('11', 'Coca cola', 'Refrigerante de sabor cola', '', 7.00, 'Bebida', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('12', 'Fanta', 'Refrigerante de sabor laranja', '', 6.00, 'Bebida', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('13', 'Guaraná Antarctica', 'Refrigerante de sabor guaraná', '', 5.00, 'Bebida', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('14', 'Suco', 'Suco de polpa de fruta', '', 4.50, 'Bebida', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('15', 'Água Mineral', 'Água proviniente de fontes naturais', '', 3.00, 'Bebida', utc_timestamp, utc_timestamp, true);

insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('16', 'Sorvete', 'Sorvete sabores diversos', '', 3.00, 'Sobremesa', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('17', 'Brownie', 'Delicioso Brownie Recheado de brigadeiro de chocolate', '', 5.00, 'Sobremesa', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('18', 'Milk Shake', 'Milk shake diversos sabores', '', 7.50, 'Sobremesa', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('19', 'Pudim de Leite', 'Pudim de leite condesado', '', 6.00, 'Sobremesa', utc_timestamp, utc_timestamp, true);
insert into produto_model(id, nome, descricao, imagem, preco, categoria, data_hora_criacao, data_hora_alteracao, status) VALUES ('20', 'Tortinha', 'Tortas doce diversos sabores', '', 3.00, 'Sobremesa', utc_timestamp, utc_timestamp, true);
