apiVersion: v1
kind: Service
metadata:
  name: tc-soat3-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      #targetPort: 80
      nodePort: 30000 # 30000 - 32767
  selector:
    app: tc-soat3