apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc-soat3-deployment
spec:
  template:
    metadata:
      name: tc-soat3
      labels:
        app: tc-soat3
    spec:
      containers:
        - name: tc-soat3-container
          image: franciscosviana/tc-soat3:v3.5
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dbhost
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: db_password
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbrootpassword
                  key: db_root_password
            - name: MP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mpaccesstoken
                  key: mp_access_token
          envFrom:
            - configMapRef:
                name: tc-soat3-configmap
          resources:
            requests:
              cpu: 1500m
              memory: 100Mi
  replicas: 2
  selector:
    matchLabels:
      app: tc-soat3