apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc-soat3-deployment
spec:
  template:
    metadata:
      name: tc-soat3
      labels:
        app: tc-soat3
    spec:
      containers:
        - name: tc-soat3-container
          image: franciscosviana/tc-soat3:v2
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: tc-soat3-configmap
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tc-soat3-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tc-soat3-secret
                  key: db_password
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tc-soat3-secret
                  key: db_root_password
            - name: MP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tc-soat3-secret
                  key: mp_access_token
          envFrom:
            - configMapRef:
                name: tc-soat3-configmap
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m
  replicas: 2
  selector:
    matchLabels:
      app: tc-soat3