apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tc-soat3-deployment
  labels:
    app: db-tc-soat3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: tc-soat3-db-persistent-volume
          persistentVolumeClaim:
            claimName: tc-soat3-db-pvc
      containers:
        - name: db-tc-soat3-container
          image: mysql:8.3.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : tc-soat3-secret
                  key :  db_root_password
          volumeMounts:
            - name: tc-soat3-db-persistent-volume
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10