apiVersion: v1
kind: PersistentVolume
metadata:
  name: tc-soat3-db-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"