name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests

  docker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker Image
      run: docker build -t franciscosviana/tc-soat3:teste-deploy .
    - name: Push Image Docker
      run: docker push franciscosviana/tc-soat3:teste-deploy
